Reworked plotting script
vGsteiger/ast-project pull request #12
Opened 2023-05-27 12:57 UTC by NikodemKch

Includes all requested types of plots except "iterations vs. difference" plot. Also, there is a small TODO which however should not have impact on the end result.

2023-05-28 10:38 UTC, vGsteiger commented
How many runs did you do per plot? I would assume around 5-10 runs per flag/complexity and so forth? Then I would introduce plots with whiskers to have the std deviation and so forth.

2023-06-01 01:35 UTC, NikodemKch commented
The main script now has a batch mode which creates the CSV needed for the plots. Added whiskers to plots.

2023-06-01 04:48 UTC, vGsteiger commented
Could you remove the log, the csvs, the init c files and add the new parameter to the readme? Other than that perfect!

2023-06-01 04:50 UTC, vGsteiger requested changes
As written, thanks for the work!

2023-06-01 04:50 UTC, vGsteiger commented on plotting/data_complexity.csv
Please remove

2023-06-01 04:50 UTC, vGsteiger commented on plotting/data_optimizations.csv
Remove

2023-06-01 04:50 UTC, vGsteiger commented on plotting/data_single.csv
Remove

2023-06-01 04:50 UTC, vGsteiger commented on plotting/data_timeouts.csv
Remove

2023-06-01 04:50 UTC, vGsteiger commented on plotting/srcreduce_cleaned.log.keep
Remove

2023-06-01 04:50 UTC, vGsteiger commented on testing_input/init0.c
Remove

2023-06-01 04:50 UTC, vGsteiger commented on src/srcreduce/main.py
> +    if args.batch_measurements is not None and not save_iters:
Please add to readme :)

2023-06-05 01:31 UTC, NikodemKch commented
Everything fixed, Percentile class improved.

2023-06-05 04:11 UTC, vGsteiger approved these changes
Great thank you!

2023-06-05 04:11 UTC, merged